# Generated by Django 3.1.7 on 2021-06-26 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addbookmodel',
            old_name='Book_name',
            new_name='Bookname',
        ),
    ]
