# Generated by Django 3.1.7 on 2021-06-26 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20210626_1437'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addbookmodel',
            old_name='Bookname',
            new_name='Book_name',
        ),
    ]
