# Generated by Django 3.1.7 on 2021-06-26 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_order_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_model',
            name='user',
        ),
    ]
